"""Initial migration

Revision ID: 4e270d0a464e
Revises: c3d4e5f6a7b8
Create Date: 2025-12-16 22:53:45.013163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e270d0a464e'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ml_models_name_key', 'ml_models', type_='unique')
    op.create_index(op.f('ix_ml_models_name'), 'ml_models', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_models_name'), table_name='ml_models')
    op.create_unique_constraint('ml_models_name_key', 'ml_models', ['name'])
    # ### end Alembic commands ###
